# Generated by Django 5.0.2 on 2024-02-23 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
